export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST"
export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS"
export const ADD_CART_ITEM_FAILURE = "ADD_CART_ITEM_FAILURE"

export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_FAILURE = "GET_CART_FAILURE"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"

export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST"
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS"
export const DELETE_CART_ITEM_FAILURE = "DELETE_CART_ITEM_FAILURE"

export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST"
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE"
